name: voyant-trove

services:
  # the front end proxy listens on port 80 and proxies incoming requests to one or other of the back end containers
  front-end-proxy:
    image: httpd
    network_mode: "host"
    volumes:
      - type: bind
        source: httpd.conf
        target: /usr/local/apache2/conf/httpd.conf
      - type: bind
        source: htdocs/
        target: /usr/local/apache2/htdocs/
  
  # the trove proxy listens on port 8080 and proxies requests to Trove's API
  # and rewrites the responses
  trove-proxy:
#    image: trove-proxy
    image: ghcr.io/conal-tuohy/troveproxy:main
    network_mode: "host"

  # the voyant container listens on port 8080 and provides a text analysis application
  voyant:
    image: voyant-docker
    network_mode: "host"
